homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 118
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize:
   group.vu:
    hidden: no
   group.dillion:
    hidden: no
     

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# New config panel
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
 base_url: nguyenha.duckdns.org
 api_password: !secret http_password
 ssl_certificate: '/etc/letsencrypt/live/nguyenha.duckdns.org/fullchain.pem'
 ssl_key: '/etc/letsencrypt/live/nguyenha.duckdns.org/privkey.pem'

# Checks for available updates
updater:

# Discover some devices automatically
discovery:


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor: !include sensors.yaml

# Text to speech
tts:
  platform: google

ifttt:
  key: !secret ifttt_api_key

notify:
  - platform: html5
    name: html5
    gcm_api_key: !secret notify_html5_gcm_api_key
    gcm_sender_id: !secret notify_html5_gcm_sender_id
  - platform: joaoapps_join
    device_id: !secret join_vu_device_id
    name: GalaxyS7
    api_key: !secret join_vu_device_api_key

joaoapps_join:
  - name: GalaxyS7
    device_id: group.GalaxyS7
    api_key: !secret join_vu_device_api_key
    
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: ha
  password: !secret mqtt_password
  protocol: 3.1
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

device_tracker:
- platform: nmap_tracker
  hosts: 192.168.1.179-183
  home_interval: 1
  consider_home: 180
  scan_options: " --privileged -sP "
  exclude:
   - 192.168.1.180
- platform: owntracks
  max_gps_accuracy: 200

media_player:
  - platform: cast
    host: 192.168.1.145
  - platform: cast
    host: 192.168.1.143
  - platform: cast
    host: 192.168.1.144
  - platform: cast
    host: 192.168.1.122
  - platform: cast
    host: 192.168.1.124
  - platform: cast
    host: 192.168.1.126  
  - platform: plex
    include_non_clients: true
    show_all_controls: true

group:
  Kitchen:
    view: yes
    entities:
      - media_player.kitchen_home
      - device_tracker.ghome
  Living Room:
    view: yes
    entities:
      - media_player.main_tv
  Office:
    view: yes
    entities:
      - media_player.office_tv
  Theater:
    view: yes
    entities:
      - media_player.fire_tv_stick
      - light.mqtt_theater_room_light
      - sensor.theater_room_motion_sensor
  Garage Door:
    view: yes
    entities:
      - sensor.gogogate2sensor
      - cover.garage_door
  Family:
    view: yes
    entities:
      - device_tracker.vnguyen972_vugalaxy7
      - device_tracker.dillion972_HungSamsung
      - device_tracker.dustin972_dustinGalaxy7
      - device_tracker.duyen972_DuyenGalaxys7
  Dark Sky Weather:
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_daily_high_apparent_temperature
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_apparent_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_daily_max_precip_intensity
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_humidity
      - sensor.dark_sky_icon
      - sensor.dark_sky_minutely_summary
      - sensor.dark_sky_nearest_storm_bearing
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_ozone
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_pressure
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature
      - sensor.dark_sky_visibility
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed

zone: !include zones.yaml

cover:
  platform: command_line
  covers:
    garage_door:
      command_open: curl --silent -X GET https://maker.ifttt.com/trigger/OpenMyGarage/with/key/bamq6_Bv89a5zqRh4XL9B?value1=Opened
      command_close: curl --silent -X GET https://maker.ifttt.com/trigger/CloseMyGarage/with/key/bamq6_Bv89a5zqRh4XL9B?value1=Opened
      command_state: /home/pi/hass.shell.commands/garage/checkG2Sensor.sh

input_select:
  trash_day:
    options:
     - Mon
     - Tue
     - Wed
     - Thu
     - Fri
     - Sat
     - Sun
    initial: Wed
      
scene:
  - name: theater light normal
    entities:
      light.mqtt_theater_room_light:
        state: on
        transition: 2
        brightness: 75
  - name: theater light dim
    entities:
      light.mqtt_theater_room_light:
        state: on
        transition: 2
        brightness: 20
  - name: theater light off
    entities:
      light.mqtt_theater_room_light:
        state: off
        transition: 2

automation: !include automations.yaml
light:
  - platform: mqtt
    name: "MQTT Theater Room Light"
    state_topic: "smartthings/Theater Room Dimmer/switch"
    command_topic: "smartthings/Theater Room Dimmer/switch"
    brightness_state_topic: "smartthings/Theater Room Dimmer/level"
    brightness_command_topic: "smartthings/Theater Room Dimmer/level"
    brightness_scale: 99
    brightness_template: "{{ value }}"
    qos: 0
    payload_on: "on"
    payload_off: "off"
    retain: true
    optimistic: false
  - platform: mqtt
    name: "MQTT Dinner Table Light"
    state_topic: "smartthings/Dinner Table Light/switch"
    command_topic: "smartthings/Dinner Table Light/switch"
    brightness_state_topic: "smartthings/Dinner Table Light/level"
    brightness_command_topic: "smartthings/Dinner Table Light/level"
    brightness_scale: 99
    brightness_template: "{{ value }}"
    qos: 0
    payload_on: "on"
    payload_off: "off"
    retain: true
    optimistic: false
emulated_hue:
  type: google_home
  listen_port: 80

remote:
  - platform: harmony
    name: Theater Room
    host: 192.168.1.196
    activity: Watch Fire TV
ecobee:
  api_key: !secret ecobee_api_key    
binary_sensor:
  - platform: workday
    country: US
    state: TX
switch:
  - platform: template
    switches:
      firetv:
        value_template: "{% if is_state('remote.theater_room', 'on') %}on{% else %}off{% endif %}"
        turn_on:
          service: remote.turn_on
          entity_id: remote.theater_room
        turn_off:
          service: remote.turn_off
          entity_id: remote.theater_room
lock:
  - platform: lockitron
    access_token: !secret lockitron_access_token
    id: !secret lockitron_lock_id
duckdns:
  domain: nguyenha
  access_token: !secret duckdns_access_token
rest_command:
  notify_googlehome_door_locked:
    url: 'https://maker.ifttt.com/trigger/FrontDoorLockStatusChanged/with/key/bamq6_Bv89a5zqRh4XL9B?value1=Locked'
    payload: >
      '{"entity_id":"media_player.nguyeniverse","message":"Front Door is {{Value1}}"}'
  notify_googlehome_door_unlocked:
    url: 'https://maker.ifttt.com/trigger/FrontDoorLockStatusChanged/with/key/bamq6_Bv89a5zqRh4XL9B?value1=Unlocked'
    payload: >
      '{"entity_id":"media_player.nguyeniverse","message":"Front Door is {{Value1}}"}'
  update_lockitron_status_locked:
    url: 'https://apilio.herokuapp.com/boolean_variables/frontDoorLocked/set_true/with_key/c1e95158a62b73f9a197de4584a841a6'
  update_lockitron_status_unlocked:
    url: 'https://apilio.herokuapp.com/boolean_variables/frontDoorLocked/set_false/with_key/c1e95158a62b73f9a197de4584a841a6'
google_assistant:
  project_id: project-5901766033282729275
  client_id: 6349238557567013A7351545817A507
  access_token: 6432z896263A400821425988
  exposed_domains:
    - switch
    - light
    - script
    - media_player
    - scene
    - automation